Digite quantidade de notas: e
invalid literal for int() with base 10: 'e'
Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 4, in <module>
    qtnotas = int(input('Digite quantidade de notas: '))
ValueError: invalid literal for int() with base 10: 'e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 7, in <module>
    print(mensagem,qtnotas)
NameError: name 'qtnotas' is not defined
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: r
invalid literal for int() with base 10: 'r'
Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 4, in <module>
    qtnotas = int(input('Digite quantidade de notas: '))
ValueError: invalid literal for int() with base 10: 'r'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 7, in <module>
    print(mensagem,str(qtnotas))
NameError: name 'qtnotas' is not defined
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: e
invalid literal for int() with base 10: 'e'
Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 4, in <module>
    qtnotas = int(input('Digite quantidade de notas: '))
ValueError: invalid literal for int() with base 10: 'e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Aula-2/exerc3.py", line 7, in <module>
    print(mensagem+str(qtnotas))
NameError: name 'qtnotas' is not defined
developer@developer:~/520$ python3 Aula-2/exerc3.py
  File "Aula-2/exerc3.py", line 8
    exit()
       ^
SyntaxError: invalid syntax
developer@developer:~/520$ e
bash: e: comando não encontrado
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: e
invalid literal for int() with base 10: 'e'
Digite somente numeros!
developer@developer:~/520$ ipython
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: nomes = ['daniel', 'maria']

In [2]: exit()
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: e
invalid literal for int() with base 10: 'e'
Digite somente numeros!
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: 11,2
invalid literal for int() with base 10: '11,2'
Digite somente numeros!
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: ^CTraceback (most recent call last):
  File "Aula-2/exerc3.py", line 4, in <module>
    qtnotas = int(input('Digite quantidade de notas: '))
KeyboardInterrupt
developer@developer:~/520$ python3 Aula-2/exerc3.py
Digite quantidade de notas: 5
Digite a nota 1: 6
Digite a nota 2: 6
Digite a nota 3: 6
Digite a nota 4: 6
Digite a nota 5: 6
Média:  6.0
Recuperação
developer@developer:~/520$ git push origin master
Username for 'https://github.com': alexandrepiza
Password for 'https://alexandrepiza@github.com':
Counting objects: 13, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (13/13), 1.75 KiB | 0 bytes/s, done.
Total 13 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/alexandrepiza/520.git
   38c819a..1e953ab  master -> master
developer@developer:~/520$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Aula-2/exerc3.py
        git_command.txt

nothing added to commit but untracked files present (use "git add" to track)
developer@developer:~/520$ git add .
developer@developer:~/520$ git push origin master
Username for 'https://github.com': alexandrepiza
Password for 'https://alexandrepiza@github.com':
Everything up-to-date
developer@developer:~/520$ python3 Aula-2/exerc4.py
Digite quantidade de notas: e
invalid literal for int() with base 10: 'e'
Digite somente numeros! Tente novamente.
developer@developer:~/520$ python3 Aula-2/exerc4.py
Digite quantidade de notas: 5
Digite a nota 2: 0
Digite a nota 3: 0
Digite a nota 4: 0
Digite a nota 5: 0
Digite a nota 6: 0
Média:  0.0
Reprovado
developer@developer:~/520$ python3 Aula-2/exerc4.py
Digite quantidade de notas: 3
Digite a nota 2: ^CTraceback (most recent call last):
  File "Aula-2/exerc4.py", line 18, in <module>
    nota = float(input('Digite a nota {}: '.format(x+1)))
KeyboardInterrupt
developer@developer:~/520$ python3 Aula-2/exerc4.py
Digite quantidade de notas: 3
Digite a nota 1: e
could not convert string to float: 'e'
Digite somente numeros! Tente novamente.
Digite a nota 1: 2
Digite a nota 2: dsg
could not convert string to float: 'dsg'
Digite somente numeros! Tente novamente.
Digite a nota 2: 6
Digite a nota 3: bb
could not convert string to float: 'bb'
Digite somente numeros! Tente novamente.
Digite a nota 3: 9
Média:  5.666666666666667
Recuperação
developer@developer:~/520$ python3 Aula-2/exerc4.py
Traceback (most recent call last):
  File "Aula-2/exerc4.py", line 4, in <module>
    while er == null:
NameError: name 'er' is not defined
developer@developer:~/520$ python3 Aula-2/exerc4.py
  File "Aula-2/exerc4.py", line 4
    while er = null:
             ^
SyntaxError: invalid syntax
developer@developer:~/520$ python3 Aula-2/exerc4.py
  File "Aula-2/exerc4.py", line 5
    try:
    ^
IndentationError: unexpected indent
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: d
Apenas números.
Traceback (most recent call last):
  File "Aula-2/exerc5.py", line 11, in <module>
    print(convidados[num])
NameError: name 'num' is not defined
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: d
Traceback (most recent call last):
  File "Aula-2/exerc5.py", line 5, in <module>
    num=int(input('Digite posição do convidado: '))
ValueError: invalid literal for int() with base 10: 'd'
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: f
Value! Apenas números.
Traceback (most recent call last):
  File "Aula-2/exerc5.py", line 13, in <module>
    print(convidados[num])
NameError: name 'num' is not defined
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: f
Value! Apenas números.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 3
Traceback (most recent call last):
  File "Aula-2/exerc5.py", line 16, in <module>
    print(convidados[num])
IndexError: list index out of range
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: r
Value! Apenas números.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 5
Traceback (most recent call last):
  File "Aula-2/exerc5.py", line 16, in <module>
    print(convidados[num])
IndexError: list index out of range
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 2
joao
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente.3
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente.3
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 4
Index! Posição na lista inexistente. Existem 3 convidados.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: ed
Value! Apenas números.
developer@developer:~/520$ python3 Aula-2/exerc5.py
Digite posição do convidado: 2
Value! Apenas números.
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagem de programação? c
Linguagem incorreta!
developer@developer:~/520$ #asldfk.asdjkl
developer@developer:~/520$ # Para dar permissão para todos os arquivos
developer@developer:~/520$ chmod +x $(ls)
developer@developer:~/520$ chmod +x $(ls)
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagem    de programação? llll
Linguagem incorreta!
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagemde programação? ^[[A
Linguagem incorreta!
developer@developer:~/520$ h
bash: h: comando não encontrado
developer@developer:~/520$ h
bash: h: comando não encontrado
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagem de programação? g
Linguagem incorreta!
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagem de programação? r
Linguagem incorreta!

Olá Mundo!

Meu nome é Alexandre
Estou ingressão no Python!
developer@developer:~/520$ python3 Aula-2/exerc6.py
Qual é a melhor linguagem de programação? g
Linguagem incorreta!

Olá Mundo!

Meu nome é Alexandre
Estou ingressão no Python!

developer@developer:~/520$ python3 Aula-2/exerc7.py
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 3, in <module>
    arquivo = open('nomes.txt','r')
FileNotFoundError: [Errno 2] No such file or directory: 'nomes.txt'
developer@developer:~/520$ python3 Aula-2/exerc7.py
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 3, in <module>
    arquivo = open('nomes.txt','r')
FileNotFoundError: [Errno 2] No such file or directory: 'nomes.txt'
developer@developer:~/520$ cd Aula-2
developer@developer:~/520/Aula-2$ python3 exerc7.py
daniel
maria
joao
pedro
alexandre
vanice
developer@developer:~/520/Aula-2$ python3 exerc7.py
daniel
maria
joao
pedro
alexandre
vanice
Traceback (most recent call last):
  File "exerc7.py", line 11, in <module>
    with open as arquivo2:
AttributeError: __exit__
developer@developer:~/520/Aula-2$ python3 exerc7.py
daniel
maria
joao
pedro
alexandre
vanice
daniel
maria
joao
pedro
alexandre
vanice
developer@developer:~/520/Aula-2$ python3 exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
developer@developer:~/520/Aula-2$ pwd
/home/developer/520/Aula-2
developer@developer:~/520/Aula-2$ ^C
developer@developer:~/520/Aula-2$ cd ..
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice']
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice']
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 18, in <module>
    print(arquivo.write('jose'))
io.UnsupportedOperation: not writable
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice']
4
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice

daniel
maria
joao
pedro
alexandre
vanice
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice']
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 20, in <module>
    print(arquivo.read())
io.UnsupportedOperation: not readable
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo

daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo']
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 20, in <module>
    print(arquivo.read())
io.UnsupportedOperation: not readable
developer@developer:~/520$ python3 Aula-2/exerc7.py
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo

daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo']

developer@developer:~/520$ python3 Aula-2/exerc7.py
Forma 1
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
jose
rodolfo

Forma 2
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
jose
rodolfo
Forma 3
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo']
Forma 4

developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4

developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4

developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
jose
rodolfo
jose
rodolfo
jose
rodolfo
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
[]
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo\n', 'jose\n', 'rodolfo']
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
jose
rodolfo
jose
rodolfo
jose
rodolfo
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
joao
pedro
alexandre
vanice
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
joao
pedro
alexandre
vanice
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
joao
pedro
alexandre
vanice
developer@developer:~/520$ python3 Aula-2/exerc7.py
  File "Aula-2/exerc7.py", line 24
    print(arquivo.read())
        ^
IndentationError: expected an indented block
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4

jose
rodolfojoao
pedro
alexandre
vanice
developer@developer:~/520$ ^C
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
Traceback (most recent call last):
  File "Aula-2/exerc7.py", line 25, in <module>
    print(arquivo.read())
io.UnsupportedOperation: not readable
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
jose
rodolfo
developer@developer:~/520$ python3 Aula-2/exerc7.py

Forma 4
daniel
maria
joao
pedro
alexandre
vanice
jose
rodolfo
developer@developer:~/520$ python3 Aula-2/exerc8.py
developer@developer:~/520$ python3 Aula-2/exerc8.py
developer@developer:~/520$ python3 Aula-2/exerc8.py
developer@developer:~/520$ python3 Aula-2/exerc8.py
developer@developer:~/520$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   Aula-2/exerc3.py
        new file:   git_command.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Aula-1/doc.txt
        modified:   git_command.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Aula-2/exerc4.py
        Aula-2/exerc5.py
        Aula-2/exerc6.py
        Aula-2/exerc7.py
        Aula-2/exerc8.py
        Aula-2/nomes.txt
        Aula-2/nomes2.txt
        Aula-2/output.txt

developer@developer:~/520$ git add .
developer@developer:~/520$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Aula-1/doc.txt
        new file:   Aula-2/exerc3.py
        new file:   Aula-2/exerc4.py
        new file:   Aula-2/exerc5.py
        new file:   Aula-2/exerc6.py
        new file:   Aula-2/exerc7.py
        new file:   Aula-2/exerc8.py
        new file:   Aula-2/nomes.txt
        new file:   Aula-2/nomes2.txt
        new file:   Aula-2/output.txt
        new file:   git_command.txt

developer@developer:~/520$ git comment -m ''
git: 'comment' is not a git command. See 'git --help'.

Did you mean this?
        commit
developer@developer:~/520$ git comment -m '15hs'
git: 'comment' is not a git command. See 'git --help'.

Did you mean this?
        commit
developer@developer:~/520$ git commint -m '15hs'
git: 'commint' is not a git command. See 'git --help'.

Did you mean this?
        commit
developer@developer:~/520$ git commit -m '15hs'
[master 96aa1a7] 15hs
 11 files changed, 920 insertions(+), 15 deletions(-)
 create mode 100644 Aula-2/exerc3.py
 create mode 100644 Aula-2/exerc4.py
 create mode 100644 Aula-2/exerc5.py
 create mode 100644 Aula-2/exerc6.py
 create mode 100644 Aula-2/exerc7.py
 create mode 100644 Aula-2/exerc8.py
 create mode 100644 Aula-2/nomes.txt
 create mode 100644 Aula-2/nomes2.txt
 create mode 100644 Aula-2/output.txt
 create mode 100755 git_command.txt
developer@developer:~/520$ python3 Aula-2/exerc9.py

Forma 3
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo']
developer@developer:~/520$ python3 Aula-2/exerc9.py

Forma 3
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo']
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    lista[x] = str(x+1)+lista[x]
TypeError: Can't convert 'int' object to str implicitly
developer@developer:~/520$ python3 Aula-2/exerc9.py
  File "Aula-2/exerc9.py", line 7
    lista[x] = '{}-{}.format(x+1,lista[x])
                                         ^
SyntaxError: EOL while scanning string literal
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    lista[x] = '{}-{}'.format(x+1,lista[x])
TypeError: Can't convert 'int' object to str implicitly
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    lista[x] = '{}-{}'.format(int(x+1),lista[x])
TypeError: Can't convert 'int' object to str implicitly
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    lista[x] = '{}-{}'.format(x,lista[x])
TypeError: list indices must be integers or slices, not str
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    lista[x] = '{}'.format(x)
TypeError: list indices must be integers or slices, not str
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 7, in <module>
    print(lista[x])
TypeError: list indices must be integers or slices, not str
developer@developer:~/520$ python3 Aula-2/exerc9.py
daniel

maria

joao

pedro

alexandre

vanice

jose

rodolfo
['daniel\n', 'maria\n', 'joao\n', 'pedro\n', 'alexandre\n', 'vanice\n', 'jose\n', 'rodolfo']
developer@developer:~/520$ python3 Aula-2/exerc9.py
['0-daniel\n ', '1-maria\n ', '2-joao\n ', '3-pedro\n ', '4-alexandre\n ', '5-vanice\n ', '6-jose\n ', '7-rodolfo ']
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 11, in <module>
    arquivo.write(lista)
TypeError: write() argument must be str, not list
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc9.py
Traceback (most recent call last):
  File "Aula-2/exerc9.py", line 18, in <module>
    for cont ,x in enumerate(conteudo):
NameError: name 'conteudo' is not defined
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc9.py
  File "Aula-2/exerc9.py", line 5
    lista2 := lista
           ^
SyntaxError: invalid syntax
developer@developer:~/520$ python3 Aula-2/exerc9.py
developer@developer:~/520$ python3 Aula-2/exerc10.py
<_io.TextIOWrapper name='/home/developer/520/Aula-2/texto.txt' mode='r' encoding='UTF-8'>
developer@developer:~/520$ python3 Aula-2/exerc10.py
['texto\n', '\n', 'texto\n', 'texto\n', 'texto\n', '\n', '\n', '\n', 'texto\n', 'texto\n', '\n', 'texto\n', 'texto']
developer@developer:~/520$ python3 Aula-2/exerc10.py
['texto\n', '\n', 'texto\n', 'texto\n', 'texto\n', '\n', '\n', '\n', 'texto\n', 'texto\n', '\n', 'texto\n', 'texto']
['texto\n', 'texto\n', 'texto\n', 'texto\n', 'texto\n', 'texto\n', 'texto\n', 'texto']
developer@developer:~/520$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Aula-2/exerc2.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Aula-2/exerc10.py
        Aula-2/exerc9.py
        Aula-2/nomes3.txt
        Aula-2/nomes4.txt
        Aula-2/texto.txt

no changes added to commit (use "git add" and/or "git commit -a")
developer@developer:~/520$ git add .
developer@developer:~/520$ git commit -m '15:40'
[master 209ad4f] 15:40
 6 files changed, 64 insertions(+)
 create mode 100644 Aula-2/exerc10.py
 create mode 100644 Aula-2/exerc9.py
 create mode 100644 Aula-2/nomes3.txt
 create mode 100644 Aula-2/nomes4.txt
 create mode 100644 Aula-2/texto.txt
developer@developer:~/520$ git push origin master
Username for 'https://github.com': alexandrepiza
Password for 'https://alexandrepiza@github.com':
Counting objects: 23, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (23/23), 7.91 KiB | 0 bytes/s, done.
Total 23 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
To https://github.com/alexandrepiza/520.git
   1e953ab..209ad4f  master -> master
developer@developer:~/520$ cd .ssh/
bash: cd: .ssh/: Arquivo ou diretório não encontrado
developer@developer:~/520$ ls
Aula-1  Aula-2  git_command.txt
developer@developer:~/520$ cd
developer@developer:~$ cd .ssh/
developer@developer:~/.ssh$ ls
id_rsa  id_rsa.pub  known_hosts  known_hosts.old
developer@developer:~/.ssh$ ssh-key
ssh-keygen   ssh-keyscan
developer@developer:~/.ssh$ ssh-key
ssh-keygen   ssh-keyscan
developer@developer:~/.ssh$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/developer/.ssh/id_rsa):
/home/developer/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/developer/.ssh/id_rsa.
Your public key has been saved in /home/developer/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:uFz5TbPwSyLoXMnY2IQkTUWrLI20iyrxENEd2c2JMvc developer@developer
The key's randomart image is:
+---[RSA 2048]----+
| . ..+.*o.       |
|. . =o+ +.       |
| .  o+o..        |
|.  . B +E.       |
| .  + * S . o    |
|o  . + @ o = o   |
| +. . * B o =    |
|...  o . . o .   |
|o     o     .    |
+----[SHA256]-----+
developer@developer:~/.ssh$ cat id_rsa
id_rsa      id_rsa.pub
developer@developer:~/.ssh$ cat id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNDgWsmJj7MnETPP9plY10darjdO6oAmIRDvYw9nFLxc1flcxS8FrCVOw4ak+ptQOPQFWd2TObWBkQjskib3hYOhAYr61LqiYTwWp07/RCa11hzyebriN8kKn7eti1ZN3Crg6YanyTulzSuAdBpbZOIDaS12wWXNykzkjSEqISG1FR00kpe2BN/KtwQ9dX+DQ+GLczMSaruCpSMcI7WIdRKG7dGxn/v9ziMBWYzLa4auJc5Rf+wxwOtRzsVvxZvn3YbMDMMyyYzYAKwm/Lt0XbUasjsy930Pbt2UiIgLoZraLUu1sXuSjTQ4RXDhfqPo1mwnW8pgYbR2sO+d6pdakV developer@developer
developer@developer:~/.ssh$ # depois copiasr a chave para o deploy key no site do github
developer@developer:~/.ssh$ # depois copiasr o link do github ssh e criar uma nova origin
developer@developer:~/.ssh$ git remote add origin2 git@github.com:alexandrepiza/520.git
fatal: Not a git repository (or any of the parent directories): .git
developer@developer:~/.ssh$ git remote add origin git@github.com:alexandrepiza/520.git
fatal: Not a git repository (or any of the parent directories): .git
developer@developer:~/.ssh$ git remote add origin2 https:// git@github.com:alexandrepiza/520.git
fatal: Not a git repository (or any of the parent directories): .git
developer@developer:~/.ssh$ git push origin master
fatal: Not a git repository (or any of the parent directories): .git
developer@developer:~/.ssh$ cd
developer@developer:~$ cd 520/
developer@developer:~/520$ git remote add origin2 https:// git@github.com:alexandrepiza/520.git
usage: git remote add [<options>] <name> <url>

    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=<push|fetch>]
                          set up remote as a mirror to push to or fetch from

developer@developer:~/520$ git remote add origin2 git@github.com:alexandrepiza/520.git
developer@developer:~/520$ git push origin2 master
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Everything up-to-date
developer@developer:~/520$ python3 Aula-2/exerc11.py
  File "Aula-2/exerc11.py", line 6
    soma(2,6))
       ^
SyntaxError: invalid syntax
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
8
None
6
None
10
None
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
8
6
10
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
8
6
10
Traceback (most recent call last):
  File "Aula-2/exerc11.py", line 19, in <module>
    print(soma())
TypeError: soma() missing 2 required positional arguments: 'x' and 'y'
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10
8
6
10
4
developer@developer:~/520$ python3 Aula-2/exerc11.py
  File "Aula-2/exerc11.py", line 16
    print('\n'soma2(y=2,x=6)) # passagem de parametros nomeado
                  ^
SyntaxError: invalid syntax
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10

 8
6
10
4
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10

8
6
10
4
developer@developer:~/520$ python3 Aula-2/exerc11.py
8
6
10

8
6
10
4
developer@developer:~/520$ python3 Aula-2/exerc12.py
10
developer@developer:~/520$ python3 Aula-2/exerc12.py
5
10

5
5
developer@developer:~/520$ python3 Aula-2/exerc12.py
5
10

5
5
developer@developer:~/520$ python3 Aula-2/exerc13.py
developer@developer:~/520$ python3 Aula-2/exerc13.py
  File "Aula-2/exerc13.py", line 3
    def numerar(nomearquivo,nomearquivo2)
                                        ^
SyntaxError: invalid syntax
developer@developer:~/520$ python3 Aula-2/exerc13.py
developer@developer:~/520$ sudo su
root@developer:/home/developer/520# systemctl stop jenkins
root@developer:/home/developer/520# systemctl stop postgresql
Failed to stop postgresql.service: Unit postgresql.service not loaded.
root@developer:/home/developer/520# systemctl stop mongodb
root@developer:/home/developer/520# systemctl stop mysql
root@developer:/home/developer/520# ss -ntlp
State      Recv-Q Send-Q                     Local Address:Port                                    Peer Address:Port
LISTEN     0      128                                    *:22                                                 *:*users:(("sshd",pid=473,fd=3))
LISTEN     0      128                                   :::80                                                :::*users:(("apache2",pid=751,fd=4),("apache2",pid=750,fd=4),("apache2",pid=749,fd=4),("apache2",pid=748,fd=4),("apache2",pid=746,fd=4),("apache2",pid=695,fd=4))
LISTEN     0      128                                   :::22                                                :::*users:(("sshd",pid=473,fd=4))
root@developer:/home/developer/520#